simpleclasses:
  sn_ia:
    - Ia
    - Ia-pec
    - Ia-02cx
    - Ia-91b
    - Ia-18byg
    - Ia-CSM
    - Type I
    - Ia-CSM?
    - Ia-03fg
    - Ia-91bg
    - Ia-91bg?
    - Ia-91T
    - Ia-norm
    - Iax
    - Ia-03fg
    - Ia?
    - Ia-91T-like
    - Ia-pec
    - Iax[02cx-like]

  baratheon:
    - Baratheon

  tde:
    - Tidal Disruption Event
    - TDE

  sn_other:
    - IIP
    - II
    - Type II
    - IIb?
    - IIn
    - Ibn?
    - Supernova
    - SLSN-I
    - Ic-BL?
    - Ic
    - Ic-SLSN
    - SLSN-II
    - Ib/c?
    - Ic?
    - IIn?
    - Ib
    - Ic-BL
    - SLSN I
    - Ib/c
    - IIb
    - II-norm
    - Ibn
    - SLSN-I?
    - II?
    - IIb-pec
    - SLSN-I.5
    - Icn
    - Ib?
    - I
    - SN

  bogus:
    - bogus
    - duplicate
    - bogus?

  unclass:
    - -
    - None

  other:
    - FBOT
    - rock
    - LRN
    - ILRT
    - Ca-rich
    - LRN?
    - afterglow

  agn:
    - AGN
    - QSO
    - AGN?
    - NLSy1?
    - NLSy
    - CLAGN
    - AGN?
    - NLS1
    - Seyfert
    - blazar
    - galaxy

  star:
    - nova
    - AM CVn
    - CV?
    - CV
    - varstar
    - Varstar
    - nova?
    - star
    - LBV
    - var

sncosmo_templates:
  SN Ia: salt2
  SN Ia?: salt2
  SN Iax: salt2
  SN Ia-CSM: salt2
  SN Ia-CSM?: salt2
  SN Ia-pec: salt2
  SN Ia-03fg: salt2
  SN Ia-norm: salt2
  SN Ia-91T: nugent-sn91t
  SN Ia-91bg: nugent-sn91bg
  SN Ia-91bg?: nugent-sn91bg
  SN Ib: v19-iptf13bvn-corr
  SN Ib?: v19-iptf13bvn-corr
  SN Ibn: v19-iptf13bvn-corr
  SN Ibn?: v19-iptf13bvn-corr
  SN Ib/c: nugent-sn1bc
  SN Ib/c?: nugent-sn1bc
  SN Ic: v19-2013ge-corr
  SN Ic?: v19-2013ge-corr
  SN Icn: v19-2013ge-corr
  SN Ic-BL: v19-2012ap-corr
  SN Ic-BL?: v19-2012ap-corr
  SN II: v19-2016bkv-corr
  SN II?: v19-2016bkv-corr
  SN II-pec: v19-2016bkv-corr
  SN IIb: v19-2016gkg-corr
  SN IIb?: v19-2016gkg-corr
  SN IIb-pec: v19-2016gkg-corr
  SN IIL: nugent-sn2l
  SN IIn: nugent-sn2n
  SN IIn?: nugent-sn2n
  SN IIP: nugent-sn2p
